/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cobaproject;

import java.awt.Color;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import view.menuSimpananFrame;

/**
 *
 * @author rizky
 */
public class reportFrame extends javax.swing.JFrame {

    /**
     * Creates new form report
     */
    public reportFrame() {
        initComponents();
        
        //set lokal
        Locale lokal = new Locale("id","ID");
        Locale.setDefault(lokal);
        
        //set fullscreen
        setExtendedState(getExtendedState()|JFrame.MAXIMIZED_BOTH);
    }
    
    public void setId(String ida){
        id.setText(ida);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportPinjam = new javax.swing.JDialog();
        pinjamlunas = new javax.swing.JButton();
        pinjambelum = new javax.swing.JButton();
        laporanPet = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        laporanAng = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        laporanSimp = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        laporanPinj = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        pinjamlunas.setText("Pinjaman Lunas");
        pinjamlunas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pinjamlunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinjamlunasActionPerformed(evt);
            }
        });

        pinjambelum.setText("Pinjaman Belum Lunas");
        pinjambelum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pinjambelum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinjambelumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reportPinjamLayout = new javax.swing.GroupLayout(reportPinjam.getContentPane());
        reportPinjam.getContentPane().setLayout(reportPinjamLayout);
        reportPinjamLayout.setHorizontalGroup(
            reportPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPinjamLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(pinjamlunas)
                .addGap(56, 56, 56)
                .addComponent(pinjambelum)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        reportPinjamLayout.setVerticalGroup(
            reportPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPinjamLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(reportPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinjamlunas)
                    .addComponent(pinjambelum))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        laporanPet.setBackground(new java.awt.Color(255, 0, 0));
        laporanPet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        laporanPet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanPetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanPetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanPetMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PETUGAS");

        javax.swing.GroupLayout laporanPetLayout = new javax.swing.GroupLayout(laporanPet);
        laporanPet.setLayout(laporanPetLayout);
        laporanPetLayout.setHorizontalGroup(
            laporanPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laporanPetLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        laporanPetLayout.setVerticalGroup(
            laporanPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laporanPetLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        laporanAng.setBackground(new java.awt.Color(255, 255, 0));
        laporanAng.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        laporanAng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanAngMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanAngMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanAngMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("ANGGOTA");

        javax.swing.GroupLayout laporanAngLayout = new javax.swing.GroupLayout(laporanAng);
        laporanAng.setLayout(laporanAngLayout);
        laporanAngLayout.setHorizontalGroup(
            laporanAngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanAngLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        laporanAngLayout.setVerticalGroup(
            laporanAngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanAngLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        laporanSimp.setBackground(new java.awt.Color(0, 0, 255));
        laporanSimp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        laporanSimp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanSimpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanSimpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanSimpMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SIMPANAN");

        javax.swing.GroupLayout laporanSimpLayout = new javax.swing.GroupLayout(laporanSimp);
        laporanSimp.setLayout(laporanSimpLayout);
        laporanSimpLayout.setHorizontalGroup(
            laporanSimpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laporanSimpLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        laporanSimpLayout.setVerticalGroup(
            laporanSimpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanSimpLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        laporanPinj.setBackground(new java.awt.Color(0, 255, 0));
        laporanPinj.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        laporanPinj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanPinjMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanPinjMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanPinjMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setText("PINJAMAN");

        javax.swing.GroupLayout laporanPinjLayout = new javax.swing.GroupLayout(laporanPinj);
        laporanPinj.setLayout(laporanPinjLayout);
        laporanPinjLayout.setHorizontalGroup(
            laporanPinjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laporanPinjLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        laporanPinjLayout.setVerticalGroup(
            laporanPinjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanPinjLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        back.setText("Kembali");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        id.setText("YOU ARE...");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("LAPORAN");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(laporanPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(laporanAng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(laporanSimp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(laporanPinj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(id)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back)
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(laporanPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laporanAng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laporanSimp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laporanPinj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(id))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void laporanPetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanPetMouseEntered
        laporanPet.setBackground(Color.PINK);
    }//GEN-LAST:event_laporanPetMouseEntered

    private void laporanPetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanPetMouseExited
        laporanPet.setBackground(Color.RED);
    }//GEN-LAST:event_laporanPetMouseExited

    private void laporanAngMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanAngMouseEntered
        laporanAng.setBackground(Color.ORANGE);
    }//GEN-LAST:event_laporanAngMouseEntered

    private void laporanAngMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanAngMouseExited
        laporanAng.setBackground(Color.YELLOW);
    }//GEN-LAST:event_laporanAngMouseExited

    private void laporanSimpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanSimpMouseEntered
        laporanSimp.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_laporanSimpMouseEntered

    private void laporanSimpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanSimpMouseExited
        laporanSimp.setBackground(Color.BLUE);
    }//GEN-LAST:event_laporanSimpMouseExited

    private void laporanPinjMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanPinjMouseEntered
        laporanPinj.setBackground(new Color(0,204,0));
    }//GEN-LAST:event_laporanPinjMouseEntered

    private void laporanPinjMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanPinjMouseExited
        laporanPinj.setBackground(Color.GREEN);
    }//GEN-LAST:event_laporanPinjMouseExited

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        berandaFrameMaster bfa = new berandaFrameMaster();
        Locale lokal = new Locale("us","US");
        Locale.setDefault(lokal);
        bfa.setId(id.getText());
        bfa.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void laporanPetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanPetMouseClicked
        try{
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("reportPetugas.jasper"), null, config.configDB());
            JasperViewer.viewReport(jp, false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_laporanPetMouseClicked

    private void laporanAngMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanAngMouseClicked
        try{
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("reportAnggota.jasper"), null, config.configDB());
            JasperViewer.viewReport(jp, false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_laporanAngMouseClicked

    private void laporanSimpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanSimpMouseClicked
        try{
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("reportSimpanan.jasper"), null, config.configDB());
            JasperViewer.viewReport(jp, false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_laporanSimpMouseClicked

    private void laporanPinjMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanPinjMouseClicked
        reportPinjam.setSize(400, 110);
        reportPinjam.setLocationRelativeTo(laporanPinj);
        reportPinjam.setVisible(true);
    }//GEN-LAST:event_laporanPinjMouseClicked

    private void pinjamlunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinjamlunasActionPerformed
        try{
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("reportPinjaman.jasper"), null, config.configDB());
            JasperViewer.viewReport(jp, false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_pinjamlunasActionPerformed

    private void pinjambelumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinjambelumActionPerformed
        try{
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("reportPinjamanBelum.jasper"), null, config.configDB());
            JasperViewer.viewReport(jp, false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_pinjambelumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reportFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel laporanAng;
    private javax.swing.JPanel laporanPet;
    private javax.swing.JPanel laporanPinj;
    private javax.swing.JPanel laporanSimp;
    private javax.swing.JButton pinjambelum;
    private javax.swing.JButton pinjamlunas;
    private javax.swing.JDialog reportPinjam;
    // End of variables declaration//GEN-END:variables
}
