/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cobaproject;

import java.awt.Color;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import view.menuSimpananFrame;

/**
 *
 * @author rizky
 */
public class reportFrameUser extends javax.swing.JFrame {

    /**
     * Creates new form report
     */
    public reportFrameUser() {
        initComponents();
        
        //set lokal
        Locale lokal = new Locale("id","ID");
        Locale.setDefault(lokal);
        
        //set fullscreen
        setExtendedState(getExtendedState()|JFrame.MAXIMIZED_BOTH);
    }
    
    public void setId(String ida){
        id.setText(ida);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelpojok1 = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        panelatas1 = new javax.swing.JPanel();
        logout1 = new javax.swing.JLabel();
        namaaplikasi = new javax.swing.JLabel();
        panelsamping = new javax.swing.JPanel();
        txtAnggota = new javax.swing.JLabel();
        laporanSal = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        laporanPinj = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        laporanSimp = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelpojok1.setBackground(new java.awt.Color(0, 255, 0));

        id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id.setForeground(new java.awt.Color(102, 102, 102));
        id.setText("YOU ARE...");

        javax.swing.GroupLayout panelpojok1Layout = new javax.swing.GroupLayout(panelpojok1);
        panelpojok1.setLayout(panelpojok1Layout);
        panelpojok1Layout.setHorizontalGroup(
            panelpojok1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpojok1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(id)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelpojok1Layout.setVerticalGroup(
            panelpojok1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelpojok1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelatas1.setBackground(new java.awt.Color(255, 255, 255));

        logout1.setForeground(new java.awt.Color(204, 0, 0));
        logout1.setText("LOGOUT");
        logout1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout1MouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout1MouseClicked(evt);
            }
        });

        namaaplikasi.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        namaaplikasi.setForeground(new java.awt.Color(0, 204, 0));
        namaaplikasi.setText("KOPERASI SIMPAN PINJAM");

        javax.swing.GroupLayout panelatas1Layout = new javax.swing.GroupLayout(panelatas1);
        panelatas1.setLayout(panelatas1Layout);
        panelatas1Layout.setHorizontalGroup(
            panelatas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelatas1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(namaaplikasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 408, Short.MAX_VALUE)
                .addComponent(logout1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        panelatas1Layout.setVerticalGroup(
            panelatas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelatas1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelatas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaaplikasi, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(logout1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelsamping.setBackground(new java.awt.Color(0, 204, 0));

        txtAnggota.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        txtAnggota.setForeground(new java.awt.Color(255, 255, 255));
        txtAnggota.setText("UBAH PROFIL");
        txtAnggota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAnggotaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAnggotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAnggotaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelsampingLayout = new javax.swing.GroupLayout(panelsamping);
        panelsamping.setLayout(panelsampingLayout);
        panelsampingLayout.setHorizontalGroup(
            panelsampingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelsampingLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(txtAnggota)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelsampingLayout.setVerticalGroup(
            panelsampingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsampingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtAnggota)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        laporanSal.setBackground(new java.awt.Color(255, 0, 0));
        laporanSal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        laporanSal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanSalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanSalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanSalMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SALDO");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout laporanSalLayout = new javax.swing.GroupLayout(laporanSal);
        laporanSal.setLayout(laporanSalLayout);
        laporanSalLayout.setHorizontalGroup(
            laporanSalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanSalLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        laporanSalLayout.setVerticalGroup(
            laporanSalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laporanSalLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        laporanPinj.setBackground(new java.awt.Color(255, 255, 0));
        laporanPinj.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        laporanPinj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanPinjMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanPinjMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanPinjMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("PINJAMAN");

        javax.swing.GroupLayout laporanPinjLayout = new javax.swing.GroupLayout(laporanPinj);
        laporanPinj.setLayout(laporanPinjLayout);
        laporanPinjLayout.setHorizontalGroup(
            laporanPinjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laporanPinjLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        laporanPinjLayout.setVerticalGroup(
            laporanPinjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanPinjLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        laporanSimp.setBackground(new java.awt.Color(0, 0, 255));
        laporanSimp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        laporanSimp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanSimpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanSimpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanSimpMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SIMPANAN");

        javax.swing.GroupLayout laporanSimpLayout = new javax.swing.GroupLayout(laporanSimp);
        laporanSimp.setLayout(laporanSimpLayout);
        laporanSimpLayout.setHorizontalGroup(
            laporanSimpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laporanSimpLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        laporanSimpLayout.setVerticalGroup(
            laporanSimpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laporanSimpLayout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("LAPORAN");

        back.setText("Kembali");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelpojok1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelsamping, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelatas1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(laporanSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 89, Short.MAX_VALUE)
                        .addComponent(laporanPinj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(laporanSimp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelpojok1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelatas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelsamping, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(laporanSal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(laporanSimp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(laporanPinj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(back)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void laporanSalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanSalMouseEntered
        laporanSal.setBackground(Color.PINK);
    }//GEN-LAST:event_laporanSalMouseEntered

    private void laporanSalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanSalMouseExited
        laporanSal.setBackground(Color.RED);
    }//GEN-LAST:event_laporanSalMouseExited

    private void laporanPinjMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanPinjMouseEntered
        laporanPinj.setBackground(Color.ORANGE);
    }//GEN-LAST:event_laporanPinjMouseEntered

    private void laporanPinjMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanPinjMouseExited
        laporanPinj.setBackground(Color.YELLOW);
    }//GEN-LAST:event_laporanPinjMouseExited

    private void laporanSimpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanSimpMouseEntered
        laporanSimp.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_laporanSimpMouseEntered

    private void laporanSimpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanSimpMouseExited
        laporanSimp.setBackground(Color.BLUE);
    }//GEN-LAST:event_laporanSimpMouseExited

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Locale lokal = new Locale("us","US");
        Locale.setDefault(lokal);
        berandaFrameUser bf = new berandaFrameUser();
        bf.setId(id.getText());
        bf.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void logout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout1MouseClicked
        Locale lokal = new Locale("us","US");
        Locale.setDefault(lokal);
        new loginFrameProject().setVisible(true);
        dispose();
    }//GEN-LAST:event_logout1MouseClicked

    private void logout1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout1MouseExited
        logout1.setForeground(Color.red);
    }//GEN-LAST:event_logout1MouseExited

    private void logout1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout1MouseEntered
        logout1.setForeground(Color.pink);
    }//GEN-LAST:event_logout1MouseEntered

    private void txtAnggotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAnggotaMouseExited
        txtAnggota.setForeground(Color.white);
    }//GEN-LAST:event_txtAnggotaMouseExited

    private void txtAnggotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAnggotaMouseEntered
        txtAnggota.setForeground(Color.gray);
    }//GEN-LAST:event_txtAnggotaMouseEntered

    private void txtAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAnggotaMouseClicked
        Locale lokal = new Locale("us","US");
        Locale.setDefault(lokal);
        formAnggotaUser fa = new formAnggotaUser();
        fa.setId(id.getText());
        fa.setVisible(true);
        dispose();
    }//GEN-LAST:event_txtAnggotaMouseClicked

    private void laporanSalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanSalMouseClicked
        try{

            String path="src/cobaproject/reportSaldoUser.jasper";
            HashMap parameter = new HashMap();
            parameter.put("idanggota",id.getText());
            JasperPrint print = JasperFillManager.fillReport(path,parameter,config.configDB());
            JasperViewer.viewReport(print, false);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane,"Dokumen Tidak Ada "+ex);
        }
    }//GEN-LAST:event_laporanSalMouseClicked

    private void laporanPinjMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanPinjMouseClicked
        try{
            String path="src/cobaproject/reportPinjamanUser.jasper";
            HashMap parameter = new HashMap();
            parameter.put("idanggota",id.getText());
            JasperPrint print = JasperFillManager.fillReport(path,parameter,config.configDB());
            JasperViewer.viewReport(print, false);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane,"Dokumen Tidak Ada "+ex);
        }
    }//GEN-LAST:event_laporanPinjMouseClicked

    private void laporanSimpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanSimpMouseClicked
        try{
            String path="src/cobaproject/reportSimpanUser.jasper";
            HashMap parameter = new HashMap();
            parameter.put("idanggota",id.getText());
            JasperPrint print = JasperFillManager.fillReport(path,parameter,config.configDB());
            JasperViewer.viewReport(print, false);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane,"Dokumen Tidak Ada "+ex);
        }
    }//GEN-LAST:event_laporanSimpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reportFrameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reportFrameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reportFrameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reportFrameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reportFrameUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel laporanPinj;
    private javax.swing.JPanel laporanSal;
    private javax.swing.JPanel laporanSimp;
    private javax.swing.JLabel logout1;
    private javax.swing.JLabel namaaplikasi;
    private javax.swing.JPanel panelatas1;
    private javax.swing.JPanel panelpojok1;
    private javax.swing.JPanel panelsamping;
    private javax.swing.JLabel txtAnggota;
    // End of variables declaration//GEN-END:variables
}
