/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import cobaproject.berandaFrameMaster;
import cobaproject.formAnggotaMaster;
import cobaproject.formPetugas;
import cobaproject.loginFrameProject;
import cobaproject.pinjam;
import cobaproject.simpan;
import cobaproject.transaksiPokok;
import cobaproject.transaksiSukarela;
import cobaproject.transaksiWajib;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author rizky
 */
public class menuSimpananFrame extends javax.swing.JFrame {

    /**
     * Creates new form menuSimpananFrame
     */
    public menuSimpananFrame() {
        initComponents();
        
        //set fullscreen
        setExtendedState(getExtendedState()|JFrame.MAXIMIZED_BOTH);
    }
    
    public void tataletakDialog(){
        dialogTransaksi.setSize(300,200);
        dialogTransaksi.setLocationRelativeTo(panelkanan);
    }
    
    public void setId(String ida){
        id.setText(ida);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPetugas = new javax.swing.JLabel();
        txtAnggota = new javax.swing.JLabel();
        txtSimpan = new javax.swing.JLabel();
        txtPinjam = new javax.swing.JLabel();
        txtAngsuran = new javax.swing.JLabel();
        dialogTransaksi = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        transaksiPokok = new javax.swing.JButton();
        transaksiWajib = new javax.swing.JButton();
        transaksiSukarela = new javax.swing.JButton();
        panelpojok = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        panelatas = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        namaaplikasi = new javax.swing.JLabel();
        panelsamping = new javax.swing.JPanel();
        txtPetugas2 = new javax.swing.JLabel();
        txtAnggota2 = new javax.swing.JLabel();
        txtSimpan2 = new javax.swing.JLabel();
        txtPinjam2 = new javax.swing.JLabel();
        txtAngsuran2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelkiri = new javax.swing.JPanel();
        txtbuat = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panelkanan = new javax.swing.JPanel();
        txttransaksi = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        txtPetugas.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        txtPetugas.setForeground(new java.awt.Color(255, 255, 255));
        txtPetugas.setText("PETUGAS");

        txtAnggota.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        txtAnggota.setForeground(new java.awt.Color(255, 255, 255));
        txtAnggota.setText("ANGGOTA");

        txtSimpan.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        txtSimpan.setForeground(new java.awt.Color(255, 255, 255));
        txtSimpan.setText("SIMPAN");

        txtPinjam.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        txtPinjam.setForeground(new java.awt.Color(255, 255, 255));
        txtPinjam.setText("PINJAM");

        txtAngsuran.setFont(new java.awt.Font("Yu Gothic", 1, 10)); // NOI18N
        txtAngsuran.setForeground(new java.awt.Color(255, 255, 255));
        txtAngsuran.setText("ANGSURAN");

        dialogTransaksi.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("TRANSAKSI SIMPANAN");

        transaksiPokok.setText("POKOK");
        transaksiPokok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transaksiPokok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiPokokActionPerformed(evt);
            }
        });

        transaksiWajib.setText("WAJIB");
        transaksiWajib.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transaksiWajib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiWajibActionPerformed(evt);
            }
        });

        transaksiSukarela.setText("SUKARELA");
        transaksiSukarela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transaksiSukarela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiSukarelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogTransaksiLayout = new javax.swing.GroupLayout(dialogTransaksi.getContentPane());
        dialogTransaksi.getContentPane().setLayout(dialogTransaksiLayout);
        dialogTransaksiLayout.setHorizontalGroup(
            dialogTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogTransaksiLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dialogTransaksiLayout.createSequentialGroup()
                        .addComponent(transaksiPokok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(transaksiSukarela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(transaksiWajib)))
                .addContainerGap())
        );
        dialogTransaksiLayout.setVerticalGroup(
            dialogTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogTransaksiLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(dialogTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transaksiPokok)
                    .addComponent(transaksiWajib)
                    .addComponent(transaksiSukarela))
                .addGap(44, 44, 44))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelpojok.setBackground(new java.awt.Color(0, 255, 0));

        id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id.setForeground(new java.awt.Color(102, 102, 102));
        id.setText("YOU ARE...");

        javax.swing.GroupLayout panelpojokLayout = new javax.swing.GroupLayout(panelpojok);
        panelpojok.setLayout(panelpojokLayout);
        panelpojokLayout.setHorizontalGroup(
            panelpojokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpojokLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(id)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelpojokLayout.setVerticalGroup(
            panelpojokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelpojokLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelatas.setBackground(new java.awt.Color(255, 255, 255));

        logout.setForeground(new java.awt.Color(204, 0, 0));
        logout.setText("LOGOUT");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });

        namaaplikasi.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        namaaplikasi.setForeground(new java.awt.Color(0, 204, 0));
        namaaplikasi.setText("KOPERASI SIMPAN PINJAM");

        javax.swing.GroupLayout panelatasLayout = new javax.swing.GroupLayout(panelatas);
        panelatas.setLayout(panelatasLayout);
        panelatasLayout.setHorizontalGroup(
            panelatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelatasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(namaaplikasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 521, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        panelatasLayout.setVerticalGroup(
            panelatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelatasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaaplikasi, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelsamping.setBackground(new java.awt.Color(0, 204, 0));

        txtPetugas2.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        txtPetugas2.setForeground(new java.awt.Color(255, 255, 255));
        txtPetugas2.setText("PETUGAS");
        txtPetugas2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtPetugas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPetugas2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPetugas2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPetugas2MouseExited(evt);
            }
        });

        txtAnggota2.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        txtAnggota2.setForeground(new java.awt.Color(255, 255, 255));
        txtAnggota2.setText("ANGGOTA");
        txtAnggota2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtAnggota2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAnggota2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAnggota2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAnggota2MouseExited(evt);
            }
        });

        txtSimpan2.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        txtSimpan2.setForeground(new java.awt.Color(255, 255, 255));
        txtSimpan2.setText("SIMPAN");
        txtSimpan2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSimpan2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSimpan2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSimpan2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSimpan2MouseExited(evt);
            }
        });

        txtPinjam2.setFont(new java.awt.Font("Yu Gothic", 1, 11)); // NOI18N
        txtPinjam2.setForeground(new java.awt.Color(255, 255, 255));
        txtPinjam2.setText("PINJAM");
        txtPinjam2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtPinjam2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPinjam2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPinjam2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPinjam2MouseExited(evt);
            }
        });

        txtAngsuran2.setFont(new java.awt.Font("Yu Gothic", 1, 10)); // NOI18N
        txtAngsuran2.setForeground(new java.awt.Color(255, 255, 255));
        txtAngsuran2.setText("ANGSURAN");

        javax.swing.GroupLayout panelsampingLayout = new javax.swing.GroupLayout(panelsamping);
        panelsamping.setLayout(panelsampingLayout);
        panelsampingLayout.setHorizontalGroup(
            panelsampingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsampingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelsampingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSimpan2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPinjam2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAngsuran2)
                    .addComponent(txtPetugas2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnggota2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelsampingLayout.setVerticalGroup(
            panelsampingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsampingLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(txtPetugas2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(txtAnggota2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(txtSimpan2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(txtPinjam2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(txtAngsuran2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        panelkiri.setBackground(new java.awt.Color(255, 255, 255));
        panelkiri.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelkiri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelkiriMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelkiriMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelkiriMouseExited(evt);
            }
        });

        txtbuat.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtbuat.setForeground(new java.awt.Color(0, 0, 204));
        txtbuat.setText("SIMPAN");

        javax.swing.GroupLayout panelkiriLayout = new javax.swing.GroupLayout(panelkiri);
        panelkiri.setLayout(panelkiriLayout);
        panelkiriLayout.setHorizontalGroup(
            panelkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelkiriLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(txtbuat)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        panelkiriLayout.setVerticalGroup(
            panelkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelkiriLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(txtbuat)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(panelkiri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(panelkiri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        panelkanan.setBackground(new java.awt.Color(255, 255, 255));
        panelkanan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelkanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelkananMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelkananMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelkananMouseExited(evt);
            }
        });

        txttransaksi.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txttransaksi.setForeground(new java.awt.Color(204, 102, 0));
        txttransaksi.setText("JENIS SIMPANAN");

        javax.swing.GroupLayout panelkananLayout = new javax.swing.GroupLayout(panelkanan);
        panelkanan.setLayout(panelkananLayout);
        panelkananLayout.setHorizontalGroup(
            panelkananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelkananLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(txttransaksi)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelkananLayout.setVerticalGroup(
            panelkananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelkananLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(txttransaksi)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(panelkanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(panelkanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        back.setText("Kembali");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelsamping, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelpojok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelatas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 114, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelpojok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelatas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelsamping, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(back)
                        .addContainerGap(40, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked

        new loginFrameProject().setVisible(true);
        dispose();

    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setForeground(Color.pink);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setForeground(Color.red);
    }//GEN-LAST:event_logoutMouseExited

    private void txtPetugas2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPetugas2MouseClicked

        new formPetugas().setVisible(true);
        dispose();
    }//GEN-LAST:event_txtPetugas2MouseClicked

    private void txtPetugas2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPetugas2MouseEntered
        txtPetugas2.setForeground(Color.gray);
    }//GEN-LAST:event_txtPetugas2MouseEntered

    private void txtPetugas2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPetugas2MouseExited
        txtPetugas2.setForeground(Color.white);
    }//GEN-LAST:event_txtPetugas2MouseExited

    private void txtAnggota2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAnggota2MouseClicked

        new formAnggotaMaster().setVisible(true);
        dispose();
    }//GEN-LAST:event_txtAnggota2MouseClicked

    private void txtAnggota2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAnggota2MouseEntered
        txtAnggota2.setForeground(Color.gray);
    }//GEN-LAST:event_txtAnggota2MouseEntered

    private void txtAnggota2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAnggota2MouseExited
        txtAnggota2.setForeground(Color.white);
    }//GEN-LAST:event_txtAnggota2MouseExited

    private void txtSimpan2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSimpan2MouseClicked

        new menuSimpananFrame().setVisible(true);
        dispose();

    }//GEN-LAST:event_txtSimpan2MouseClicked

    private void txtSimpan2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSimpan2MouseEntered
        txtSimpan2.setForeground(Color.gray);
    }//GEN-LAST:event_txtSimpan2MouseEntered

    private void txtSimpan2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSimpan2MouseExited
        txtSimpan2.setForeground(Color.white);
    }//GEN-LAST:event_txtSimpan2MouseExited

    private void panelkiriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelkiriMouseClicked
        simpan simp = new simpan();
        simp.setAkses(id.getText());
        simp.setVisible(true);
        dispose();
    }//GEN-LAST:event_panelkiriMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        berandaFrameMaster bfa = new berandaFrameMaster();
        bfa.setId(id.getText());
        bfa.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void panelkiriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelkiriMouseEntered
        panelkiri.setBackground(new Color(240,240,240));
        txtbuat.setForeground(new Color(153,0,153));
    }//GEN-LAST:event_panelkiriMouseEntered

    private void panelkiriMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelkiriMouseExited
        panelkiri.setBackground(Color.white);
        txtbuat.setForeground(Color.blue);
    }//GEN-LAST:event_panelkiriMouseExited

    private void panelkananMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelkananMouseEntered
        panelkanan.setBackground(new Color(240,240,240));
        txttransaksi.setForeground(Color.red);
    }//GEN-LAST:event_panelkananMouseEntered

    private void panelkananMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelkananMouseExited
        panelkanan.setBackground(Color.white);
        txttransaksi.setForeground(new Color(204,102,0));
    }//GEN-LAST:event_panelkananMouseExited

    private void panelkananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelkananMouseClicked
        tataletakDialog();
        dialogTransaksi.setVisible(true);
    }//GEN-LAST:event_panelkananMouseClicked

    private void transaksiPokokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiPokokActionPerformed
        transaksiPokok tp = new transaksiPokok();
        tp.setAkses(id.getText());
        tp.setVisible(true);
        dialogTransaksi.dispose();
        dispose();
        
    }//GEN-LAST:event_transaksiPokokActionPerformed

    private void transaksiSukarelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiSukarelaActionPerformed
        transaksiSukarela ts = new transaksiSukarela();
        ts.setAkses(id.getText());
        ts.setVisible(true);
        dialogTransaksi.dispose();
        dispose();
    }//GEN-LAST:event_transaksiSukarelaActionPerformed

    private void transaksiWajibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiWajibActionPerformed
        transaksiWajib tw = new transaksiWajib();
        tw.setAkses(id.getText());
        tw.setVisible(true);
        dialogTransaksi.dispose();
        dispose();
    }//GEN-LAST:event_transaksiWajibActionPerformed

    private void txtPinjam2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPinjam2MouseClicked
        pinjam p = new pinjam();
        p.setId(id.getText());
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_txtPinjam2MouseClicked

    private void txtPinjam2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPinjam2MouseEntered
        txtPinjam2.setForeground(Color.gray);
    }//GEN-LAST:event_txtPinjam2MouseEntered

    private void txtPinjam2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPinjam2MouseExited
        txtPinjam2.setForeground(Color.white);
    }//GEN-LAST:event_txtPinjam2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuSimpananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuSimpananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuSimpananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuSimpananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuSimpananFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JDialog dialogTransaksi;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel namaaplikasi;
    private javax.swing.JPanel panelatas;
    private javax.swing.JPanel panelkanan;
    private javax.swing.JPanel panelkiri;
    private javax.swing.JPanel panelpojok;
    private javax.swing.JPanel panelsamping;
    private javax.swing.JButton transaksiPokok;
    private javax.swing.JButton transaksiSukarela;
    private javax.swing.JButton transaksiWajib;
    private javax.swing.JLabel txtAnggota;
    private javax.swing.JLabel txtAnggota2;
    private javax.swing.JLabel txtAngsuran;
    private javax.swing.JLabel txtAngsuran2;
    private javax.swing.JLabel txtPetugas;
    private javax.swing.JLabel txtPetugas2;
    private javax.swing.JLabel txtPinjam;
    private javax.swing.JLabel txtPinjam2;
    private javax.swing.JLabel txtSimpan;
    private javax.swing.JLabel txtSimpan2;
    private javax.swing.JLabel txtbuat;
    private javax.swing.JLabel txttransaksi;
    // End of variables declaration//GEN-END:variables
}
